In [1]:
import numpy as np

In [2]:
array=[1,2,3,4,5]

In [3]:
print(array)

[1, 2, 3, 4, 5]


In [4]:
print(type(array))

<class 'list'>


In [6]:
array=array*2

In [7]:
print(array)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [8]:
array=np.array(array)

In [9]:
print(array)

[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]


In [10]:
print(type(array))

<class 'numpy.ndarray'>


In [11]:
array=array*2

In [12]:
print(array)

[ 2  4  6  8 10  2  4  6  8 10  2  4  6  8 10  2  4  6  8 10]


In [13]:
brray=np.array([1,2,3,4,5,6,7,8,9,0])

In [14]:
print(brray)

[1 2 3 4 5 6 7 8 9 0]


In [ ]:
print(array+brray) #error detection for different dimension

ValueError: operands could not be broadcast together with shapes (20,) (10,) 