In [16]:
import numpy as np


In [17]:
array = np.array(1)

In [18]:
print(array)

1


In [37]:
                                            # find dimentions

In [19]:
print(array.ndim)

0


In [20]:
array = np.array([1,2,3,4,5,6,7,8,9,0])    #array is a 1 dimention

In [21]:
print(array)
print(array.ndim)

[1 2 3 4 5 6 7 8 9 0]
1


In [45]:
                                        # note all start in 0 (row,colums,layers,element)-----------------------------------------------------------

In [22]:
mat = np.array([
                 [1,2,3],
                 [4,5,6]   
                ])

In [23]:
print(mat)                            # matrix is a multiple arrays 
print(mat.ndim)                       # matrix is a 2 dimention 

[[1 2 3]
 [4 5 6]]
2


In [24]:
arr = np.array([
                 [ [1,2,3],
                   [4,5,6] ],

                 [ [11,22,33],
                   [44,55,66] ]
                ])

In [ ]:
print(arr)
print(f"{arr.ndim} dimentions")             
print(f"{arr.nbytes} bytes")

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]
3 dimentions
96 bytes


In [25]:
print(arr)
print(arr.dtype)
print(f"{arr.ndim} dimentions")
print(f"{arr.nbytes} bytes")

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]
int64
3 dimentions
96 bytes


In [27]:
brr = np.array([
                    [  [1,2,3],
                       [4,5,6] ],

                    [  [7,8,9],
                       [77,88,99] ],

                    [  [11,22,33],
                       [44,55,66]  ]
                ])

In [ ]:
print(brr)
print(brr.ndim)                    

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [77 88 99]]

 [[11 22 33]
  [44 55 66]]]
3


In [29]:
# array 1 dimention
# matrix 2 dimentions
# multiple matrix 3 dimentions 

In [38]:
                                                #find each element & row

In [ ]:
                                        # 01. one metrix

In [30]:
print(mat)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(mat[0])  # 0 row

[1 2 3]


In [ ]:
print(mat[0][0])  # 0,0 place element

1


In [35]:
# i need 6 ,so 6 in 1st row and 2nd colums
print(mat[1][2])

6


In [40]:
                                        # multiple matrix 

In [41]:
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [ ]:
print(arr[1][1][2])          #layers,row,colums

66


In [43]:
# i need 22 , so 22 in 1st layer , 0th row , 1st colums 
print(arr[1][0][1])

22


In [ ]:
# i need 5 , so 0th layyers , 1st row, 1st colums
print(arr[0][1][1])
# method 2
print(arr[0,1,1])

5
5


In [48]:
# i need 22 , so 22 in 1st layer , 0th row , 1st colums 
print(arr[1,0,1])

22


In [ ]:
                                    #shape

In [50]:
print(mat)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(mat.shape)            # Answer =(2,3)  meaning 2 rows and 3 colums

(2, 3)


In [ ]:
print(array)
print(array.shape)   # Answer =(10,)  array is a single dimention & 10 elements

[1 2 3 4 5 6 7 8 9 0]
(10,)


In [53]:
                                        # shape change

In [54]:
print(array)
array = array.reshape(5,2)
print(array)

[1 2 3 4 5 6 7 8 9 0]
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


In [55]:
array = array.reshape(2,5)

In [56]:
print(array)

[[1 2 3 4 5]
 [6 7 8 9 0]]


In [58]:
array = array.reshape(1,10)

In [59]:
print(array)

[[1 2 3 4 5 6 7 8 9 0]]


In [ ]:
array = array.reshape(5,2)
# { array = array.rechape(-1,2) } = { array = array.reshape(5,-1) } = { array = array.reshape(5,2) }
# -1 is come, you focuse next value (row or colums)

In [61]:
print(array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


In [63]:
array = array.reshape(-1,2)

In [64]:
print(array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


In [65]:
array = array.reshape(-1,5)

In [66]:
print(array)

[[1 2 3 4 5]
 [6 7 8 9 0]]
