In [2]:
import numpy as np

In [3]:
arr = np.array([
                    [1,2,3],
                    [4,5,6],
                    [7,8,9]
                ])

In [4]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
                                                        # 01.row Slicing 

In [5]:
                                    # zero based indexing (start in 0 (row,colums,elements,layers))

In [6]:
print(arr[2])  # 2th row

[7 8 9]


In [7]:
print(arr[1,1])  # 1th row & 1th colums

5


In [8]:
print(arr[0]) # 0th row

[1 2 3]


In [9]:
                                            # negative indexing (down to up)
                                            # -1 last row,   

In [10]:
print(arr[-1])  

[7 8 9]


In [11]:
print(arr[-2])

[4 5 6]


In [12]:
print(arr[-3])

[1 2 3]


In [13]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
                                        # find between rows
                                        # arr[0:2] meaning  (0th row) =< (print_value)< (2nd row) 
                                        # arr[1:]  meaning  (1th row) =< (print_value) ---->(not come 0th row & come 1,2 row)
                                        # arr[:2]  meaning               (print_value)< (2nd row) ---->(not come 2nd row & come 0,1 row)   

In [15]:
print(arr[1:2])

[[4 5 6]]


In [16]:
print(arr[0:2])

[[1 2 3]
 [4 5 6]]


In [17]:
print(arr[1:])

[[4 5 6]
 [7 8 9]]


In [18]:
print(arr[:2])

[[1 2 3]
 [4 5 6]]


In [ ]:
                                        # arr(start:stop:step)
            # step mean ---> step=2 so 1st row take, 2nd row skip, 3rd row take, 4th row skip, 5th row take,................
                            # step=3 so 1st row take, (2,3) row skip, 4th row take, (5,6) row skip, 7th row take,................

In [19]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
print(arr[0:2:2])

[[1 2 3]]


In [21]:
print(arr[0:2:1])

[[1 2 3]
 [4 5 6]]


In [22]:
print(arr[1:2:2])

[[4 5 6]]


In [29]:
print(arr[0:2:3])

[[1 2 3]]


In [ ]:
                                                    # 02.colums Slicing 
                                                #  [:]=row , [:,]=colums

In [31]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
print(arr[:,1])

[2 5 8]


In [34]:
#i need 0th colums
print(arr[:,0])

[1 4 7]


In [40]:
print(arr[:,0:1])      #[:, = colums :start:stop]

[[1]
 [4]
 [7]]


In [36]:
print(arr[:,0:2])

[[1 2]
 [4 5]
 [7 8]]


In [38]:
print(arr[:,0:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
print(arr[:,0:0])

[]


In [46]:
print(arr[:,0:3:1])     #[:,=colums,:start:stop:step]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
print(arr[:,0:3:2]) 

[[1 3]
 [4 6]
 [7 9]]


In [48]:
print(arr[:,0:3:3]) 

[[1]
 [4]
 [7]]


In [ ]:
print(arr[:,0:3:4])       

[[1]
 [4]
 [7]]


In [ ]:
                                                    # Slicing Syntax                                    
                                # arr[row_start : row_end : step , col_start : col_end : step]

In [54]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(arr[1:3:1 , 1:3:1])            # arr[row_start : row_end : step , col_start : col_end : step]

[[5 6]
 [8 9]]


In [ ]:
print(arr[0:2:1 , 0:2:1])                # arr[row_start : row_end : step , col_start : col_end : step]

[[1 2]
 [4 5]]


In [55]:
print(arr[0:2:1 , 1:3:1])

[[2 3]
 [5 6]]
